name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    # Deployment to GitHub Pages
    - name: Deploy to GitHub Pages
      if: ${{ github.ref == 'refs/heads/main' }} # Only deploy on pushes to the main branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # Deploy to the gh-pages branch
        folder: public     # Deploy the contents of the public folder
        token: ${{ secrets.GH_TOKEN }}  # Use the Personal Access Token for authentication
